version: "3"

services:
  app-volumes:
    build: ./config/docker/image/app-volumes
    volumes: &appvolumes
      - .:/var/www/html:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock
      - app-vendor:/var/www/html/vendor
      - app-generated:/var/www/html/generated
      - app-var:/var/www/html/var
      - pub-static:/var/www/html/pub/static
      - pub-media:/var/www/html/pub/media
      - integration-test-sandbox:/var/www/html/dev/tests/integration/tmp

  app:
    build: ./config/docker/image/nginx
    ports:
      - 80:8000
    volumes: *appvolumes
    depends_on:
      - phpfpm

  phpfpm:
    image: modestcoders/php:7.1-fpm
    volumes: *appvolumes
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - app-volumes
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - dbdata:/var/lib/mysql

  unison:
    image: modestcoders/unison:2.51.2
    volumes:
      - app-vendor:/var/www/html/vendor
      - app-generated:/var/www/html/generated
      - ./vendor:/sync/vendor
      - ./generated:/sync/generated
    environment:
      - SYNC_SOURCE_BASE_PATH=/sync
      - SYNC_DESTINATION_BASE_PATH=/var/www/html
      - SYNC_MAX_INOTIFY_WATCHES=60000
    depends_on:
      - app-volumes
    privileged: true

  node:
    image: modestcoders/node-php:node8-php7.1
    volumes: *appvolumes
    environment:
      - NPM_CONFIG_PREFIX=/home/app/.npm-global # To avoid permission error on npm install. It tries to save it at /var/www (root is the owner)
    depends_on:
      - app-volumes

volumes:
  dbdata:
  sockdata:
  app-vendor:
  app-generated:
  app-var:
  pub-static:
  pub-media:
  integration-test-sandbox:
